In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env=gym.make("FrozenLake-v0")

In [4]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n
print(action_space_size,state_space_size)

4 16


In [5]:
Q_table=np.zeros((state_space_size,action_space_size))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
num_episodes=100000
max_steps_per_episodes=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.01

In [50]:
rewards=[]

for episode in range(num_episodes):
    
    state=env.reset() #reset the env to starting point
    
    done=False
    reward_current_episode=0 #to save rewards of the current epiosode
    
    for step in range(max_steps_per_episodes):
        
        exploaration_rate_threshold=random.uniform(0,1)
        
        if(exploaration_rate_threshold>exploration_rate):
            
            action=np.argmax(Q_table[state,:])
        
        else:
            
            action=env.action_space.sample()
        
        new_state,reward,done,info=env.step(action)
        
        #updating the Q
        Q_table[state,action]=(Q_table[state,action]*(1-learning_rate))+(reward+discount_rate*np.max(Q_table[new_state,:]))*learning_rate
        
        state=new_state
        
        reward_current_episode=reward_current_episode+reward
        
        if(done==True):
            break
            
    #exploration decay
    exploration_rate=min_exploration_rate+(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    rewards.append(reward_current_episode)

In [51]:
print('======================Q Table======================\n',Q_table)

======================Q Table======================
 [[0.53668642 0.49086014 0.48498933 0.48025646]
 [0.34907004 0.35234319 0.34725324 0.48844795]
 [0.4142586  0.40951092 0.40162504 0.45898447]
 [0.39707226 0.29602548 0.28766559 0.4350137 ]
 [0.55443244 0.29959559 0.29542422 0.30066851]
 [0.         0.         0.         0.        ]
 [0.33320201 0.15676945 0.21076191 0.11425949]
 [0.         0.         0.         0.        ]
 [0.36859706 0.44952389 0.40262537 0.58194983]
 [0.49437416 0.62382049 0.27333371 0.462842  ]
 [0.61704336 0.41650256 0.47249309 0.33894911]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.54816808 0.59319805 0.70846012 0.53488001]
 [0.75799384 0.85357284 0.76182558 0.72879085]
 [0.         0.         0.         0.        ]]


In [52]:
rewards_per_thousand_episodes=np.split(np.array(rewards),num_episodes/1000)

for i,array in enumerate(rewards_per_thousand_episodes):
    print(i+1,'-1000, average reward:',np.mean(array))

1 -1000, average reward: 0.494
2 -1000, average reward: 0.693
3 -1000, average reward: 0.693
4 -1000, average reward: 0.687
5 -1000, average reward: 0.699
6 -1000, average reward: 0.665
7 -1000, average reward: 0.712
8 -1000, average reward: 0.658
9 -1000, average reward: 0.692
10 -1000, average reward: 0.7
11 -1000, average reward: 0.687
12 -1000, average reward: 0.722
13 -1000, average reward: 0.687
14 -1000, average reward: 0.674
15 -1000, average reward: 0.69
16 -1000, average reward: 0.691
17 -1000, average reward: 0.72
18 -1000, average reward: 0.67
19 -1000, average reward: 0.693
20 -1000, average reward: 0.681
21 -1000, average reward: 0.689
22 -1000, average reward: 0.674
23 -1000, average reward: 0.662
24 -1000, average reward: 0.694
25 -1000, average reward: 0.716
26 -1000, average reward: 0.699
27 -1000, average reward: 0.675
28 -1000, average reward: 0.68
29 -1000, average reward: 0.673
30 -1000, average reward: 0.671
31 -1000, average reward: 0.674
32 -1000, average rewar

In [55]:
#Playing the game using trained Q values

for episode in range(5):
    
    state=env.reset()
    done=False
    print('============Episode:',episode+1,'============')
    time.sleep(1)
    
    for step in range(max_steps_per_episodes):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action=np.argmax(Q_table[state,:])
        new_state,reward,done,info=env.step(action)
        
        if done==True:
            clear_output(wait=True)
            env.render()
            
            if reward==1:
                print('======Goal Reached======')
                time.sleep(3)
            else:
                print('======Hole Reached======')
                time.sleep(3)
            
            clear_output(wait=True)
            break
            
        state=new_state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
======Goal Reached======
