In [1]:
#pip install gym
import gym

env=gym.make("FrozenLake-v0")

In [2]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n

print(action_space_size,state_space_size)

4 16


In [3]:
import numpy as np

Q_table=np.zeros((state_space_size,action_space_size))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
#testing the environment
from IPython.display import clear_output
import time as t

done=False

env.reset()

action_dict={0:'Left',1:'Down',2:'Right',3:'Up'}

while(not done):
    
    action=np.random.randint(0,4,1)[0]
    new_state,reward,done,info=env.step(action)
    print(new_state,reward,done,action_dict[action])
    env.render()
    t.sleep(3)
    clear_output(wait=True)

5 0.0 True Down
  (Down)
SFFF
FHFH
FFFH
HFFG


In [10]:
num_episodes=100000
max_steps_per_episodes=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.01

In [13]:
import random

rewards=[]

for episode in range(num_episodes):
    
    state=env.reset()
    done=False
    current_reward=0
    
    while(not done):
        
        exploaration_rate_threshold=random.uniform(0,1)
        
        if(exploaration_rate_threshold>exploration_rate):
            
            action=np.argmax(Q_table[state,:])   #exploitation
        
        else:
            
            action=env.action_space.sample()    #exploration
        
        #perform the action
        new_state,reward,done,info=env.step(action)
        
        #updating the Q
        Q_table[state,action]=(Q_table[state,action]*(1-learning_rate))+(reward+discount_rate*np.max(Q_table[new_state,:]))*learning_rate  
        
        #state change
        state=new_state
        
        current_reward=current_reward+reward
        
        if(done==True):
            break
    
    exploration_rate=min_exploration_rate+(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    rewards.append(current_reward)

In [14]:
print('======================Q Table======================\n',Q_table)

======================Q Table======================
 [[0.53203982 0.5022373  0.49598616 0.49822111]
 [0.38386325 0.24712009 0.31090362 0.51393418]
 [0.39091918 0.41306361 0.40432606 0.47892859]
 [0.34248827 0.34240872 0.30979709 0.45069393]
 [0.54238296 0.43212603 0.39912397 0.34367376]
 [0.         0.         0.         0.        ]
 [0.30557414 0.16368169 0.14597505 0.11991735]
 [0.         0.         0.         0.        ]
 [0.3786673  0.37253586 0.46255245 0.57927813]
 [0.37523086 0.63270485 0.38389203 0.44598003]
 [0.59519845 0.33144866 0.36167184 0.3956302 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.3672431  0.6101612  0.72158659 0.4491779 ]
 [0.71686739 0.84228796 0.72499297 0.73801185]
 [0.         0.         0.         0.        ]]


In [15]:
rewards_per_thousand_episodes=np.split(np.array(rewards),num_episodes/1000)

for i,array in enumerate(rewards_per_thousand_episodes):
    print(i+1,'-1000, average reward:',np.mean(array))

1 -1000, average reward: 0.142
2 -1000, average reward: 0.188
3 -1000, average reward: 0.209
4 -1000, average reward: 0.177
5 -1000, average reward: 0.191
6 -1000, average reward: 0.454
7 -1000, average reward: 0.643
8 -1000, average reward: 0.676
9 -1000, average reward: 0.679
10 -1000, average reward: 0.655
11 -1000, average reward: 0.684
12 -1000, average reward: 0.645
13 -1000, average reward: 0.656
14 -1000, average reward: 0.659
15 -1000, average reward: 0.697
16 -1000, average reward: 0.655
17 -1000, average reward: 0.671
18 -1000, average reward: 0.693
19 -1000, average reward: 0.663
20 -1000, average reward: 0.703
21 -1000, average reward: 0.722
22 -1000, average reward: 0.637
23 -1000, average reward: 0.653
24 -1000, average reward: 0.689
25 -1000, average reward: 0.696
26 -1000, average reward: 0.691
27 -1000, average reward: 0.635
28 -1000, average reward: 0.676
29 -1000, average reward: 0.681
30 -1000, average reward: 0.638
31 -1000, average reward: 0.703
32 -1000, average

In [20]:
for episode in range(5):
    print("Episode :",episode)

    done=False

    state=env.reset()

    action_dict={0:'Left',1:'Down',2:'Right',3:'Up'}

    while(not done):

        action=np.argmax(Q_table[state,:])
        new_state,reward,done,info=env.step(action)
        print(new_state,reward,done,action_dict[action])
        env.render()
        t.sleep(0.5)
        clear_output(wait=True)
        state=new_state

5 0.0 True Left
  (Left)
SFFF
FHFH
FFFH
HFFG
